version: "3.9"

services:
  profile_api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "50053:50053"
      - "8081:8081"
    environment:
      - MONGO_USERNAME=${MONGO_USERNAME}
      - MONGO_PASSWORD=${MONGO_PASSWORD}
      - MONGO_HOST=${MONGO_HOST}
      - MONGO_PORT=${MONGO_PORT}
    networks:
      - backend 

networks:
  backend:
    external: true
