grpc:
    protoc --go_out=. --go_opt=paths=source_relative --go-grpc_out=. --go-grpc_opt=paths=source_relative internal/server/grpc/proto/profile.proto

# docker:
#     docker network create shared_network

# gen:
# 	mockgen -source="internal/service/service.go" -destination="internal/service/mocks/mock.go"
# 	mockgen -source="internal/server/proto/epub_grpc.pb.go" -destination="internal/server/proto/mocks/mock.go"
# 	mockgen -source="internal/repository/repository.go" -destination="internal/repository/mocks/mock.go"